spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Baseone111/tutorial.git
          clone-on-start: true
  application:
    name: config-server2


server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

