#spring.application.name=User-Service

spring:
  application:
    name: User-Service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  management:
    endpoints:
      web:
        exposure:
          include: refresh
    health:
      circuitbreakers:
        enabled: true
