#spring.application.name=Missing-Person-Service
spring:
  application:
    name: Missing-Person-Service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  management:
    endpoints:
      web:
        exposure:
          include: refresh